module.exports = constant = {
	STATUS_SUCCESS: "success",
	STATUS_FAILURE: "failure",
	SOMETHING_WRONG_MSG: "Something went wrong",
	TOKEN_INVALID_MSG: "Invalid Token",
	AUTHENTICATION_ERR_MSG: "Authentication error. Token required.",
	PASSWORD_NOT_MATCH_MSG: "Forbidden! Password does not match",
	FORBIDDEN_ACTIONS_MSG: "Forbidden! You're not authorized to perform this action",
	USER_REGISTER_SUCCESS_MSG: "User successfully registered",
	LOGIN_SUCCESS: "Logged In successful",
	USER_UPDATED_SUCCESS_MSG: "user successfully updated!",
	USER_LOGOUT_MSG: "User successfully Logout",
	USER_NOT_FOUND_MSG: "User not found",
	USER_ALREADY_EXISTS_MSG: "User already exists",
	BAD_REQ_MSG: "Bad Request",
	SERVER_ERR: "Internal server error",
	USER_ID_NOT_FOUND: "User id is not there!",
	USER_ALREADY_FOLLOWED_MSG: "You already followed this user",
	USER_FOLLOWED_SUCCESS_MSG: "User successfully followed this user",
	USER_UNFOLLOWED_SUCCESS_MSG: "User successfully unfollowed this user",
	USER_NOT_FOLLOWED_MSG: "You are not following this user",
	TWEET_POSTED_SUCCESS: "Tweet posted successfully",
	TWEET_UPDATED_SUCCESS: "Tweet updated successfully",
	TWEET_DELETE_SUCCESS: "Tweet deleted successfully",
	TWEET_LIKED_MSG: "The tweet has been liked",
	TWEET_DILIKED_MSG: "The tweet has been disliked",


	//HTTP Status codes
	HTTP_200_CODE: 200,
	HTTP_201_CODE: 201,
	HTTP_204_CODE: 204,
	HTTP_206_CODE: 206,
	HTTP_400_CODE: 400,
	HTTP_401_CODE: 401,
	HTTP_403_CODE: 403,
	HTTP_404_CODE: 404,
	HTTP_409_CODE: 409,
	HTTP_422_CODE: 422,
};
